name: 文档问题
description: 提交文档错误或建议
labels: ["documentation", "待处理"]

fields:
  - name: "标题"
    required: true
    default: "[文档] 描述问题标题"

  - name: "文档链接"
    required: true
    description: "指出问题的文档 URL 或路径"

  - name: "具体问题"
    required: true
    description: "描述文档中的错误或需要改进的地方"

  - name: "修改建议"
    required: false
    description: "如果有，请提供修改建议或修正内容"
